# Generated by Django 3.2.3 on 2021-05-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_upvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
